# SFTP Connection Settings
sftp:
  host: "105.57.243.148"
  port: 27922
  username: "seokjun.yun"
  password: "S@msung26!"
  base_path: "/opt/vz_raw_data"

# Local Path Settings
paths:
  archive: "/mnt/data/sea_vzw_raw_data/archive/"
  untar: "/mnt/data/sea_vzw_raw_data/untar"
  temp: "/mnt/data/sea_vzw_raw_data/tmp/"
  log: "logs/"

# Concurrency Settings
concurrent: 1

# Keyword list file path
keyword_list_file: "family_list.txt"
